version: "3"
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - composer

  composer:
    image: composer
    volumes:
      - ./src:/app
      - ./vendor:/app/vendor
    working_dir: /app
    command: install
